### ISSUE TITLE
关于boxes格式请求帮助

### ISSUE THREAD

**Issue by csliuchang** [JDAI-CV/centerX#25]
看到您在coco_class 里面将coco标签从xywh转换为xyxy了，detertron2中训练时候也将boxes转为为xyxy了吗？

**Comment by CPFLAME** [comment]
是的  最后detectron2的数据读取格式全部转化成了统一的xyxy格式

**Comment by csliuchang** [comment]
谢谢您的回复，刚开始接触d2，最近准备把所有anchor-free用detectron2集成在一起试试。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JDAI-CV/centerX"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月2日(星期二) 下午5:04
收件人:&nbsp;"JDAI-CV/centerX"<centerX@noreply.github.com&gt;;
抄送:&nbsp;"柳昌"<598306303@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JDAI-CV/centerX] 关于boxes格式请求帮助 (#25)





 
是的  最后detectron2的数据读取格式全部转化成了统一的xyxy格式

**Comment by CPFLAME** [comment]
加油💪

**Comment by csliuchang** [comment]
最近使用detectron2上使用balloon数据集进行单分类检测时候，
当num_classes设置为1，在json文件中将我自己的类category_id 设置为0，预测出来AP一直徘徊0-5左右
当将json里面category_id 设置为1时候，预测出来AP也在0-5左右（和coco数据集id排序一致，没有0）
当我设置num_class=80预测单分类，等多个epoch之后采取测试这样保证id预测出来是正确的测试结果为AP=50
可以问下您这里大概哪个地方有问题需要怎么改呢

**Comment by CPFLAME** [comment]
盲猜可能是BASE_LR的问题，
num_class=80用默认的BASE_LR可能是没有问题的，
num_class=1的时候把BASE_LR调低点试试再跑吧

**Comment by csliuchang** [comment]
我试试呢

**Comment by csliuchang** [comment]
原来学习率是5e-5了 用的ADAMW的优化器，我调到5e-6 和5e-3都试了下，AP结果还是一样很小很小，就是不知道为啥分80类时候结果是正常的分1类就崩了。。。。
